. ~/.profile

# setfont ter-124b
KEYTIMEOUT=1

# [ ! -b /dev/mapper/storage ] && udisksctl mount
# [ ! -b /dev/mapper/media ]

case "${TTY#/dev/tty}" in
	1) command -V i3 >/dev/null && { pgrep i3 || startx } ;;
	2) ;;
	3) tmux new -s work ;;
	# *) exec tmux new -s "${TTY#/dev/}" ;;
esac
