#!/bin/sh

# Common operations
alias xx='chmod u+x'
alias x-='chmod -x'
alias th='touch'
alias md='mkdir'
# open
alias o='$OPENER'
alias n='$EDITOR'
alias s='$EDITOR "$(ff -L ~/.config ~/.local/bin ~/bin)"'

lt() { tree -aC "$@" | less -rF; }
dul() { du -ahd 1 "$@" | sort -h | less -FX; }
v() { LESSOPEN="|preview %s" less -r -F "${1:-.}"; }
ff() {  find "$@" ! -wholename '*.git*' \( -type d -printf '%p/\n' , ! -type d -print \) | fzf -m; }
senv() { source "$HOME/Applications/virtualenvs/${1:-main}/bin/activate"; }

lfcd () {
	[ $# -gt 0 ] && [ -z "$1" ] && return 2
	# cd "$(command lf -print-last-dir "$@")"

	tmp="$(mktemp)"
	command lf -last-dir-path="$tmp" "$@"
	if [ -f "$tmp" ]; then
	    dir="$(cat "$tmp")"
	    rm -f "$tmp"
	    if [ -d "$dir" ]; then
		if [ "$dir" != "$(pwd)" ]; then
		    cd "$dir"
		fi
	    fi
	fi
}

# Dirs
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

alias 1='pushd -1'
alias 2='pushd -2'
alias 3='pushd -3'
alias 4='pushd -4'
alias 5='pushd -5'
alias 6='pushd -6'
alias 7='pushd -7'
alias 8='pushd -8'
alias 9='pushd -9'

## Default options
alias rm='rm -Iv'
alias cp='cp -iv'
alias mv='mv -iv'
alias du='du -h'
alias mkdir='mkdir -pv'
alias watch='watch -c -n 1 '
alias wget='wget -c'
alias fzf='fzf --ansi'
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias tree='tree -C'
alias ls='ls -h --group-directories-first --color=auto --classify=auto'
alias info='info --vi-keys --init-file ~/.config/infokey'
alias gtypist="gtypist $GTYPIST_OPTS"

# userful aliases
alias l='ls -hAF --group-directories-first --color=always'
alias ll='l -l'
alias typ='launch-gtypist "$(sed "/^gtypist lesson - \(.*\)$/!d; s//\1/" ~/Documents/Notes/QuickNote.md)"'

