#!/bin/sh

gui -e

# pidof -q syncthing || syncthing --no-restart --no-browser \
# 	--logfile=~/.cache/syncthing/logs --log-max-size=0 \
# 	--log-max-old-files=0 >/dev/null &

if ! pidof -q copyq; then
	numlockx on &
	dunst &
	copyq &
	{ remap -x; remap; } &
fi

setdp
